export const PACKET_SIZE = {
  SMALL: 100,
  MEDIUM: 1400,
  LARGE: 60000,
}

export const PORT = {
  SENDER: 8080,
  RECEIVER: 8081,
} ;

export const HOSTNAME = 'localhost';

export const TRANSMISSION_ID_SIZE = 2;

export const SEQUENCE_NUMBER_SIZE = 4;

export const HASH_SIZE = 16;

export const TRANSMISSION_START_MESSAGE = "START";

export const TRANSMISSION_END_MESSAGE = "END";

export const SEQUENCE_NUMBER_OFFSET = TRANSMISSION_ID_SIZE;

export const HASH_OFFSET = SEQUENCE_NUMBER_OFFSET + SEQUENCE_NUMBER_SIZE;

export const MESSAGE_OFFSET = SEQUENCE_NUMBER_OFFSET + SEQUENCE_NUMBER_SIZE;

export const FITST_PACKET_MESSAGE_OFFSET = SEQUENCE_NUMBER_OFFSET + SEQUENCE_NUMBER_SIZE + HASH_SIZE;

export const MAX_RETRIES = 5;